# Generated by Django 4.2.6 on 2024-02-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_balance_type', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_balance', models.IntegerField(default=0, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('current_balance', models.IntegerField(default=0, null=True)),
                ('bank_status', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Employee_Blood_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.RenameModel(
            old_name='Employee_Additional_Loan',
            new_name='Fin_Employee_Additional_Loan',
        ),
        migrations.RenameModel(
            old_name='Employee_Loan_History',
            new_name='Fin_Employee_History',
        ),
        migrations.RenameModel(
            old_name='Employee_loan_comments',
            new_name='Fin_Employee_loan_comments',
        ),
        migrations.RenameModel(
            old_name='Employee_History',
            new_name='Fin_Employee_Loan_History',
        ),
        migrations.RenameModel(
            old_name='Employee_Loan_Repayment',
            new_name='Fin_Employee_Loan_Repayment',
        ),
        migrations.RenameModel(
            old_name='Employee_Loan_Transactions',
            new_name='Fin_Employee_Loan_Transactions',
        ),
        migrations.RenameModel(
            old_name='Loan',
            new_name='Fin_Loan',
        ),
        migrations.RenameModel(
            old_name='Loan_Term',
            new_name='Fin_Loan_Term',
        ),
        migrations.RenameField(
            model_name='fin_employee_history',
            old_name='login_details',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='fin_employee_loan_history',
            old_name='login',
            new_name='login_details',
        ),
        migrations.RemoveField(
            model_name='fin_employee_history',
            name='employee_loan',
        ),
        migrations.RemoveField(
            model_name='fin_employee_loan_history',
            name='employee',
        ),
        migrations.AddField(
            model_name='fin_employee_history',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.employee'),
        ),
        migrations.AddField(
            model_name='fin_employee_loan_history',
            name='employee_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_loan'),
        ),
        migrations.DeleteModel(
            name='Employee_Blood_Group',
        ),
    ]
