# Generated by Django 4.2.6 on 2024-02-07 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0003_fin_employee_loan_transactions_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_employee_loan_transactions_history',
            name='additional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_employee_additional_loan'),
        ),
        migrations.AddField(
            model_name='fin_employee_loan_transactions_history',
            name='repayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_employee_loan_repayment'),
        ),
    ]
