# Generated by Django 4.2.6 on 2024-02-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0003_loan_term'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan_Term',
            new_name='Employee_Loan_Term',
        ),
    ]
