# Generated by Django 4.2.6 on 2024-02-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0004_fin_employee_loan_transactions_history_additional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_employee_loan_history',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
