# Generated by Django 4.2.6 on 2024-01-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0004_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=255, null=True),
        ),
    ]
