# Generated by Django 4.2.6 on 2024-02-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0004_rename_loan_term_employee_loan_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.employee_loan_term'),
        ),
    ]
