# Generated by Django 4.2.6 on 2024-02-08 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0005_alter_fin_employee_loan_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_employee_loan_history',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
