# Generated by Django 4.2.6 on 2024-02-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0006_employee_loan_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
