# Generated by Django 4.2.6 on 2024-02-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0006_alter_fin_employee_loan_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_loan',
            name='transaction_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
