# Generated by Django 4.2.6 on 2024-02-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0007_alter_loan_loan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_loan_term',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
