# Generated by Django 4.2.6 on 2024-02-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0008_alter_employee_loan_term_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_loan_term',
            name='term_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
