# Generated by Django 4.2.6 on 2024-01-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0009_employee_loan_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_loan_transactions',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_loan_transactions',
            name='particulars',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
