# Generated by Django 4.2.6 on 2024-01-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0011_employee_loan_transactions_repayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_loan_repayment',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
