# Generated by Django 4.2.6 on 2024-01-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0013_employee_loan_transactions_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='total_loan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
