# Generated by Django 4.2.6 on 2024-01-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0014_loan_total_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_additional_loan',
            name='new_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
