# Generated by Django 4.2.6 on 2024-01-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0015_employee_additional_loan_new_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_loan_transactions',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
